### ISSUE TITLE
Invalid projection

### ISSUE THREAD

**Issue by rclark** [mapbox/mapnik-omnivore#90]
Using a tif downloaded from http://www.gisat.cz/content/en/products/data-download, omnivore is unable to determine the projection of this file.

```
digest ~/tmp/strange-projection.tif 

/Users/r/gh/mapbox/mapnik-omnivore/lib/raster.js:78
  var current = new mapnik.Projection(this.projection);
                ^
Error: failed to initialize projection with: ''
    at Raster.getExtent (/Users/r/gh/mapbox/mapnik-omnivore/lib/raster.js:78:17)
    at Raster.getCenter (/Users/r/gh/mapbox/mapnik-omnivore/lib/raster.js:67:8)
    at /Users/r/gh/mapbox/mapnik-omnivore/index.js:80:12
    at pop (/Users/r/gh/mapbox/mapnik-omnivore/node_modules/queue-async/queue.js:24:14)
    at /Users/r/gh/mapbox/mapnik-omnivore/node_modules/queue-async/queue.js:38:39
    at /Users/r/gh/mapbox/mapnik-omnivore/index.js:75:7
    at Object.oncomplete (fs.js:108:15)
```

`gdalinfo` gives the projection information as:

```
LOCAL_CS["KRON        D211",
    UNIT["metre",1,
        AUTHORITY["EPSG","9001"]]]
Origin = (-907000.000000000000000,-933000.000000000000000)
Pixel Size = (250.000000000000000,-250.000000000000000)
```

cc @GretaCB @bsudekum

**Comment by knutole** [comment]
I got here from getting the same error on same file. :8ball: Did you get anywhere with this?

**Comment by BergWerkGIS** [comment]
> Using a tif downloaded from http://www.gisat.cz/content/en/products/data-download

Don't know if it helps, but using the same tiff with `Gauss-Kruger (S-42)` projection works.

![image](https://cloud.githubusercontent.com/assets/4549888/7068024/d837df44-decf-11e4-84be-74ec42f3e069.png)


gdalwarp (`gdalwarp -t_srs EPSG:3857 MOS_CZ_GK3_250.tif mos_wm.tif`) can reproject the Gauss-Krueger one (so should mapnik-omnivore and node-gdal) and it then overlays nicely with Web Mercator tiles:

![image](https://cloud.githubusercontent.com/assets/4549888/7067950/4cd76992-decf-11e4-8e61-df596b0741ff.png)

**Comment by BergWerkGIS** [comment]
The `Krovak (S-JTSK)` seems to be `EPSG:2065` http://spatialreference.org/ref/epsg/2065/

So forcing the source srs to `EPSG:2065` produces an acceptable result on the `Krovak tif`:

```
gdalwarp -s_srs EPSG:2065 -t_srs EPSG:3857 MOS_CZ_KR_250.tif mos_wm.tif
```

![image](https://cloud.githubusercontent.com/assets/4549888/7068254/632537c2-ded1-11e4-9a60-24d7cd5d9dab.png)

**Comment by knutole** [comment]
Thanks for the clarification of this particular raster. The problem I'm having, though, is wanting to do automatic detection of projection, and for some reason `gdalinfo` returns `EPSG:9001`. Which doesn't make sense for many reasons, one being that it doesn't exist (apparently). Projections are tricky!

**Comment by BergWerkGIS** [comment]
As I see it the `EPSG:9001` just refers to the *unit of measure*

<pre>
LOCAL_CS["KRON        D211",
    <b>UNIT["metre",1,
        AUTHORITY["EPSG","9001"]]]</b>
</pre>

and not to the whole projection (`LOCAL_CS["KRON D211"`).

[epsg-registry.org on EPSG:9001](http://www.epsg-registry.org/report.htm?type=selection&entity=urn:ogc:def:uom:EPSG::9001&reportDetail=short&style=urn:uuid:report-style:default-with-code&style_name=OGP%20Default%20With%20Code&title=EPSG:9001)

I don't think there is a way to do automatic detection with files like these, that don't a have a coordinate system that can be found in the epsg registry.

**Comment by knutole** [comment]
Ok, thanks again for your clarification. I believe you're right. Thanks for your help!
